Added programmatic support to focus or blur elements
DNNCommunity/dnn-elements pull request #1119
Opened 2024-07-23 20:38 UTC by valadas

All elements that are interactable with now support programmatic focus or blur.

This is a follow up on #1116 which was working but not great: 1: Elements already have a built-in focus and blur methods as long as they have a tabIndex. 2: It was giving a stencil compiler warning that developers should not define methods with the same names as the DOM already have.

This solution is simpler and covers all the interactable elements.

Closes #1055

2024-07-23 20:40 UTC, valadas commented
Oh, just to explain a little, the Host (our component) passes the focus or blur call to the first focusable element it contains. Our component has a tabIndex if it is not already focused. When it is already focuses, it does not have a tabIndex because that would cause the whole thing to be displayed with the focused style when doing `shift-tab` to go back up the component tree.

2024-07-24 02:43 UTC, david-poindexter requested changes
Just one small thing.  I love this approach by the way!  🎉

2024-07-24 02:43 UTC, david-poindexter commented on packages/stencil-library/src/components/dnn-monaco-editor/dnn-monaco-editor.tsx
> +    console.log("focusing element");
```suggestion
```

2024-07-24 02:49 UTC, david-poindexter approved these changes

2024-07-24 02:52 UTC, merged